#!/usr/bin/env node

/**
 * Generates a reusable frame strip for the Twin Preview experiment.
 *
 * This script extracts evenly spaced WebP frames from the source MP4 and
 * writes both the frame files (public/twin-frames/frame-XXX.webp) and a
 * manifest (src/content/twinFrames.ts) so the React component can import
 * the list statically.
 */

const fs = require('node:fs');
const path = require('node:path');
const ffmpeg = require('fluent-ffmpeg');
const ffmpegInstaller = require('@ffmpeg-installer/ffmpeg');

ffmpeg.setFfmpegPath(ffmpegInstaller.path);

const FRAME_COUNT = Number(process.env.TWIN_FRAMES_COUNT) || 72;
const FRAME_WIDTH = Number(process.env.TWIN_FRAMES_WIDTH) || 1280;
const FRAME_EXTENSION = process.env.TWIN_FRAMES_EXT || 'png';
const SOURCE_VIDEO = path.resolve(__dirname, '../public/videos/twin-xform.mp4');
const FRAMES_DIR = path.resolve(__dirname, '../public/twin-frames');
const MANIFEST_PATH = path.resolve(__dirname, '../src/content/twinFrames.ts');
const OUTPUT_PATTERN = path.join(FRAMES_DIR, `frame-%03d.${FRAME_EXTENSION}`);

const ensureSourceVideo = () => {
  if (!fs.existsSync(SOURCE_VIDEO)) {
    console.error(`Source video not found at ${SOURCE_VIDEO}`);
    process.exit(1);
  }
};

const prepareOutputDir = () => {
  fs.rmSync(FRAMES_DIR, { recursive: true, force: true });
  fs.mkdirSync(FRAMES_DIR, { recursive: true });
};

const writeManifest = () => {
  const files = fs
    .readdirSync(FRAMES_DIR)
    .filter((file) => file.endsWith(`.${FRAME_EXTENSION}`))
    .sort();

  if (!files.length) {
    console.error('No frames were generated.');
    process.exit(1);
  }

  const importComment =
    '// Auto-generated by scripts/generateTwinFrames.js — do not edit manually.\n';
  const entries = files.map((file) => `  '/twin-frames/${file}',`).join('\n');

  const contents = `${importComment}export const TWIN_FRAMES = [\n${entries}\n] as const;\n`;
  fs.writeFileSync(MANIFEST_PATH, contents);
  console.log(`Updated manifest with ${files.length} frames at ${MANIFEST_PATH}`);
};

const run = () => {
  ensureSourceVideo();
  prepareOutputDir();

  console.log('Generating Twin Preview frames...');
  console.log(`Source: ${SOURCE_VIDEO}`);
  console.log(`Output: ${FRAMES_DIR}`);
  console.log(`Frames: ${FRAME_COUNT} @ width ${FRAME_WIDTH}px (${FRAME_EXTENSION})`);

  ffmpeg(SOURCE_VIDEO)
    .outputOptions([
      '-vf',
      `scale=${FRAME_WIDTH}:-1`,
      '-vframes',
      String(FRAME_COUNT),
      ...(FRAME_EXTENSION === 'png'
        ? ['-compression_level', '2']
        : ['-compression_level', '6']),
    ])
    .output(OUTPUT_PATTERN)
    .on('end', () => {
      console.log('Frame extraction complete.');
      writeManifest();
    })
    .on('error', (error) => {
      console.error('Failed to generate frames:', error.message || error);
      process.exit(1);
    })
    .run();
};

run();

